name = "AITBreg"
uuid = "ec7d80bb-0406-4476-82ea-59e600a3d9b1"
repo = "https://github.com/berkonat/AITBreg.git"
description = "Julia registry for AITB and its dependent packages."

[packages]
3e8ccfd2-c8b0-11ea-32f1-f3a5990fd77a = { name = "ACE", path = "A/ACE" }
